name: build

on:
  pull_request:
    branches:
      - main
      - next

  push:
    branches:
      - main
      - next

jobs:
  build-publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout
      - name: Setup node 16
        uses: actions/setup-node
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn
      - run: yarn test
      - run: yarn build
        env:
          BASE_PATH: /markdownclap
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Publish only with the latest commit.
          # Source: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan.
          force_orphan: true
